Fix: missing forward declaration of functions
When the project is build with makeEspArduino the compiler complains with
following errors:

	/tmp/mkESP/ulisp-esp_generic/ulisp-esp.ino.cpp: In function 'void errorsub(symbol_t, const char*)':
	/tmp/mkESP/ulisp-esp_generic/ulisp-esp.ino.cpp:299:7: error: 'pserial' was not declared in this scope; did you mean 'Serial'?
	  299 |   pfl(pserial); pfstring(PSTR("Error: "), pserial);
	      |       ^~~~~~~
	      |       Serial
	/tmp/mkESP/ulisp-esp_generic/ulisp-esp.ino.cpp:299:3: error: 'pfl' was not declared in this scope
	  299 |   pfl(pserial); pfstring(PSTR("Error: "), pserial);
	...
	...
	...

There isn't forward declaration of the functions.
Therefor declaration of functions is added.

Signed-off-by: Ivo Borisov Shopov <ivoshopov@gmail.com>